openapi: 3.0.0
info:
  version: 1.0.0
  title: API Documentation for transfer requests
servers:
  - url: https://courageous-hen-houndstooth.cyclic.cloud
    description: 'Production server'
  - url : localhost:3000
    description: 'Development server'

components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Enter the token with the word Bearer'
  schemas:
    BadRequest:
          type: object
          properties:
            error:
              type: string

paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  pattern: '^[^\s]+$' # no whitespace
                  example: user
                password:
                  type: string
                  minLength: 8 # password min length 8 character
                  pattern: "^[a-zA-Z0-9]*$" # alphanumeric
                role:
                  type: string
                  enum:
                    - 'maker'
                    - 'approver'
              required:
                - username
                - password
                - role
      responses:
        '200':
          description: 'User Created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      username:
                        type: string
                      role:
                        type: string
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'

  /auth/login:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: 'Login Success'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: string
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'

  /transfers:
    get:
      tags:
        - Transfer
      security:
        - bearer_auth: []
      responses:
        '200':
          description: List of transfers
        '401':
          description: 'Unauthorized'

  /transfers/money:
    post:
      tags:
        - Transfer
      security:
        - bearer_auth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                sourceAccount:
                  type: string
                destinationAccount:
                  type: string
              required:
                - amount
                - sourceAccount
                - destinationAccount
      responses:
        '200':
          description: Transfer created successfully
        '400':
          description: 'Invalid request'
        '401':
          description: 'Unauthorized'

  /transfers/{transferId}:
    patch:
      tags:
        - Transfer
      security:
        - bearer_auth: []
      parameters:
        - name: transferId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum:
                    - 'approved'
                    - 'rejected'
              required:
                - status
      responses:
        '200':
          description: Transfer status updated successfully
        '400':
          description: 'Invalid request'
        '401':
          description: 'Unauthorized'
